[styleTitle]
StringAlign=CENTER
StringCase=UPPER
StringEffect=SHADOW
FontEffectColor=0,0,0,40
FontColor=#colorText#
FontFace=#fontName#
FontSize=16
AntiAlias=1
ClipString=1

[styleLeftText]
StringAlign=LEFT
StringCase=NONE
StringEffect=SHADOW
FontEffectColor=0,0,0,40
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleRightText]
StringAlign=RIGHT
StringCase=NONE
StringEffect=SHADOW
FontEffectColor=0,0,0,40
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1


[styleBar1]
BarColor=#color1#
BarOrientation=Vertical
SolidColor=0,0,0,50


[styleBar2]
BarColor=#color2#
BarOrientation=Vertical
SolidColor=0,0,0,50

[styleBar3]
BarColor=#color3#
BarOrientation=Vertical
SolidColor=0,0,0,50

[styleBar4]
BarColor=#color4#
BarOrientation=Vertical
SolidColor=0,0,0,50